# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - "main"
      - features/*
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: List contents
      shell: pwsh
      run: Get-ChildItem -Recurse '/home/runner/work/MstTrx/MstTrx'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/bin/
          **/obj/
          **/*.dll
          **/*.exe
          **/*.pdb
        retention-days: 1

    - name: Test 1
      shell: pwsh
      run: | 
        dotnet test --no-build --verbosity normal `
          --filter FullyQualifiedName~MstTrx1

    - name: Test 2
      shell: pwsh
      run: | 
        dotnet test --no-build --verbosity normal `
          --filter FullyQualifiedName~MstTrx2

  test:
    needs: build
    name: Test - ${{ matrix.test-suite.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        test-suite:
          - name: "Test 1"
            filters: "FullyQualifiedName~MstTrx1"
          - name: "Test 2"
            filters: "FullyQualifiedName~MstTrx2"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: List contents
      shell: pwsh
      run: Get-ChildItem -Recurse '/home/runner/work/MstTrx/MstTrx'

    - name: Test
      shell: pwsh
      run: | 
        dotnet test --no-build --verbosity normal `
          --filter ${{ matrix.test-suite.filters }}

    - name: Publish test report
      uses: phoenix-actions/test-reporting@v15
      with:
        name: "Test Report - ${{ matrix.test-suite.name }}"
        path: ./**/TestResults/*.trx
        reporter: dotnet-trx
        output-to: step-summary