# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - "main"
      - features/*
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore  -c Debug -f net8.0

    - name: List contents
      shell: pwsh
      run: |
        Get-ChildItem -Recurse 'D:\a\MstTrx\MstTrx' `
          | ForEach-Object { Write-Host $_.FullName }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/bin/
          **/obj/
          **/*.dll
          **/*.exe
          **/*.pdb
          **/*.json
          **/*.cs
          **/*.csproj
          **/*.sln
          **/*.config
        retention-days: 1

    - name: Pre-test 1
      shell: pwsh
      run: | 
        dotnet test --no-build --verbosity normal -c Debug -f net8.0 `
          -- --filter-namespace 'MstTrx1*'

    - name: Pre-test 2
      shell: pwsh
      run: | 
        dotnet test --no-build --verbosity normal -c Debug -f net8.0 `
          -- --filter-namespace 'MstTrx2*'

  test:
    needs: build
    name: Test - ${{ matrix.test-suite.name }}
    runs-on: windows-latest
    timeout-minutes: 30

    strategy:
      matrix:
        test-suite:
          - name: "Test 1"
            filters: "--filter-namespace 'MstTrx1*'"
          - name: "Test 2"
            filters: "--filter-namespace 'MstTrx2*'"

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: List contents after download
      shell: pwsh
      run: |
        Get-ChildItem -Recurse 'D:\a\MstTrx\MstTrx' `
          | ForEach-Object { Write-Host $_.FullName }

    - name: Test after download
      shell: pwsh
      run: | 
        dotnet test --no-build --verbosity normal -c Debug -f net8.0 `
          -- ${{ matrix.test-suite.filters }}

    - name: Restore dependencies
      run: dotnet restore -c Debug -f net8.0

    - name: Build
      run: dotnet build --no-restore -c Debug -f net8.0

    - name: Test after build
      shell: pwsh
      run: | 
        dotnet test --no-build --verbosity normal -c Debug -f net8.0 `
          -- ${{ matrix.test-suite.filters }}

    - name: Publish test report
      uses: phoenix-actions/test-reporting@v15
      with:
        name: "Test Report - ${{ matrix.test-suite.name }}"
        path: ./**/TestResults/*.trx
        reporter: dotnet-trx
        output-to: step-summary